# Generated by Django 3.2.4 on 2021-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cooking_time',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=3),
        ),
        migrations.AddField(
            model_name='pizza',
            name='state',
            field=models.CharField(choices=[('RAW', 'Raw'), ('DONE', 'Done')], default='RAW', max_length=4),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pastry',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='secret_ingredient',
            field=models.CharField(default='', max_length=128),
        ),
    ]
