# Generated by Django 3.2.4 on 2021-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20210726_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='state',
            field=models.CharField(choices=[('RAW', 'Raw'), ('COOKING', 'Cooking'), ('DONE', 'Done')], default='RAW', max_length=7),
        ),
    ]
