# Generated by Django 3.2.4 on 2021-07-13 07:09

import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('date_opened', models.DateField(null=True, validators=[api.validators.not_future])),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Rating must be greater than 0!'), django.core.validators.MaxValueValidator(5, 'Rating must be 5 or lower!')])),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.TextField(validators=[django.core.validators.EmailValidator])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Fight Helicopter'), ('U', 'Unknown')], max_length=1)),
                ('job', models.CharField(choices=[('WTR', 'Waiter'), ('CLN', 'Cleaner'), ('CK', 'Cook'), ('GRD', 'Guard')], max_length=3)),
                ('birth_date', models.DateField(validators=[api.validators.not_future])),
                ('date_joined', models.DateField(validators=[api.validators.not_future])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cheese', models.CharField(blank=True, max_length=128)),
                ('pastry', models.CharField(blank=True, max_length=128)),
                ('secret_ingredient', models.CharField(blank=True, max_length=128)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
        ),
    ]
