# Generated by Django 3.2.4 on 2021-06-29 10:08

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[api.validators.validate_iin])),
            ],
        ),
    ]
